### ISSUE TITLE
screenshot_url doesn't seem to work

### ISSUE THREAD

**Issue by danielbachhuber** [stephenharris/wp-readme-to-markdown#11]
![image](https://cloud.githubusercontent.com/assets/36432/6942773/9a2038ec-d83e-11e4-84ca-e89bc7e1ade8.png)

Something I'm doing wrong?

**Comment by stephenharris** [comment]
Options need to inside `options` object. It should read:

```
files: {
    ...
},
options:{
   screenshot_url: ...
}
```

**Comment by danielbachhuber** [comment]
Yeah, just realized :smile: Thanks!
