### ISSUE TITLE
Linkify contributors

### ISSUE THREAD

**Issue by danielbachhuber** [stephenharris/wp-readme-to-markdown#12]
Feature request :)

It would be nice if the contributors were automagically linked to their profiles.wordpress.org profiles.

**Comment by stephenharris** [comment]
:+1: - will this open for anyone to submit a PR for, but will otherwise implement this myself when I get a chance

**Comment by danielbachhuber** [comment]
Sounds good

**Comment by stephenharris** [comment]
Thanks @claudiosmweb. Apologies it took so long to finally publish this update.

**Comment by claudiosmweb** [comment]
@stephenharris no worry, thanks :)
