### ISSUE TITLE
Plugin description typo

### ISSUE THREAD

**Issue by michaelbeil** [stephenharris/wp-readme-to-markdown#13]
I think you mean "converts" and not "Ccnverts" :).
 
![screen shot 2015-04-12 at 3 26 48 pm](https://cloud.githubusercontent.com/assets/4752949/7107355/628d5c8c-e128-11e4-944f-84ec7e56fef9.png)

**Comment by stephenharris** [comment]
Ha! Thanks for pointing that out :). Fixed.

**Comment by michaelbeil** [comment]
No worries! Thanks for making wp-readme-to-markdown :).
