### ISSUE TITLE
default screenshot_url broken

### ISSUE THREAD

**Issue by DanielDent** [stephenharris/wp-readme-to-markdown#14]
1. The README currently states a default screenshot_url which is different from what the source code seems to use.
2. The current default URL in the source code appears to generate broken links. The following seems compatible with Wordpress.org's current URL scheme: https://s.w.org/plugins/{plugin}/{screenshot}.png

**Comment by danielbachhuber** [comment]
I think WordPress.org changed the URLs again :(

**Comment by stephenharris** [comment]
Is this the new URL? I'm still seeing the one this plugin uses. Perhaps it applies only to new plugins?

Unless all URLs are being ported across to the new structure I'd be wary of changing the default as it will break existing users if they haven't set the screenshot URL explicitly.

Perhaps the readme should make the reader aware of the fact that there are different URL structures too.

It should be https rather than http though.

**Comment by danielbachhuber** [comment]
> Is this the new URL? I'm still seeing the one this plugin uses. Perhaps it applies only to new plugins?

Huh. Might be worth chatting with @otto42 in the #meta channel in Making WordPress.

Our screenshots were accessible at the ps.w.org domain for Shortcake Bakery, but they recently broke https://github.com/wp-shortcake/shortcake-bakery/pull/144

**Comment by Otto42** [comment]
If you need URLs for plugin screenshots, then you should get them from the APIs. Or, more to the point, you should not use the w.org CDN for anything outside of WordPress itself. We make no guarantees as to it except for uses on WordPress instances and on WordPress.org.

Plugin screenshot URLs can only reliably come from the API. Not from any other location, and certainly not built programmaticly. .

**Comment by stephenharris** [comment]
Thanks for your input @Otto42. On the basis of that I'd like to suggest the following:

 - Default `screenshot_url` to `false`
 - Only display the screenshot section if `screenshot_url` is set to something.

I think the screenshot section not appearing is better than those 404 image boxes. Furthermore that would prompt the user to actually decide where they want to serve their screenshots from. 

I'd like to point out that the only assumption is that the filenames follow the `screenshot-x` convention. So, even now, you could:

 1. If the screenshots are committed to the repo, use a relative path to the screenshots
 2. Use any publicly available URL that serves your images

(2) could be pretty much anything, your own website or, at your own risk, whichever w.org url is working for you.  My personal preference is (1).

**Comment by danielbachhuber** [comment]
@stephenharris Your proposal makes sense to me.

@Otto42 Thanks for clarifying. I wasn't wasn't aware the screenshot URLs were intended to be private.

**Comment by Otto42** [comment]
@danielbachhuber They're not intended to be private, but they're probably not guessable accurately either.

Look at the first screenshot URL for Jetpack: 
https://ps.w.org/jetpack/assets/screenshot-1.png?rev=1279667

The ps.w.org domain is a caching reverse proxy onto plugins.svn, and the rev is needed for the cachebusting. The rev is the last revision they updated anything in the /assets directory. We store that URL, and serve it via the API calls to WordPress sites.

For a plugin still keeping their screenshots in /trunk or /tags, we use a different process and those will be located on s.w.org with a different method. This isn't common anymore, but some older plugins still have it.

Point being that it's not going to be easily predictable. Better to ask the API. We don't mind you using the screenshots for whatever, but if you try to build the URLs yourself like this, then you're gonna have a hard time of it.

**Comment by DanielDent** [comment]
The Wordpress.org API looks extremely accessible.

E.g. for the jetpack plugin, simply access https://api.wordpress.org/plugins/info/1.0/jetpack.json and look at the screenshots item.

http://codex.wordpress.org/WordPress.org_API has additional info.

**Comment by stephenharris** [comment]
@DanielDent  It is, ansd feel free to write up a pull request if you have time. (Perhaps the API could be used when the screnshot setting is set to 'auto', in any case I think proceeding as I've outlined above is case (default: no screenshots).

**Comment by stephenharris** [comment]
Finally got round to publishing this. Default is now false, but you can revert to existing behaviour. 

@DanielDent an `auto` option would be nice, but not something I have the time to build right now. Feel free to open an issue/PR if you want this.

**Comment by gagan0123** [comment]
Assuming, that mostly users are using GitHub or GitLab, and they create package.json having following data:
```
"repository": {
    "type": "git",
    "url": "https://github.com/my_cool_repo"
},
```
We can also use 
```
screenshot_url: '<%= pkg.repository.url %>/raw/master/assets/{screenshot}.png'
```
Provided they have this line in grunt.initConfig
```
pkg: grunt.file.readJSON( 'package.json' )
```

That way, the **README.md** will always have correct paths to the screenshots based on where the repo is hosted, even when you haven't pushed the code to the SVN.
