### ISSUE TITLE
Bug in "Parse contributors"

### ISSUE THREAD

**Issue by pfefferle** [stephenharris/wp-readme-to-markdown#3]
There is a bug in the "Parse contributors" code...

I have a code block in my readme

`header('Content-Type: application/xrd+xml; charset=' . get_bloginfo('charset'), true);`

and the result is:

`**      header('Content-Type:** application/xrd+xml; charset=' . get_bloginfo('charset'), true);`

**Comment by stephenharris** [comment]
Thanks @marcochiesi I've made some changes to your original PR, but this should be fixed now. I'll be publishing a new release shortly.
