### ISSUE TITLE
I added few things in the parse, do you want it?

### ISSUE THREAD

**Issue by KingYes** [stephenharris/wp-readme-to-markdown#5]
I just fork your great repo (https://github.com/KingYes/wp-readme-to-markdown-with-extra), and I added some things (Travis Icon, Grunt Icon, david-dm).

You can see this in action here: https://github.com/KingYes/wordpress-aryo-activity-log

Good job @stephenharris ! :)

**Comment by rdoursenaud** [comment]
Why don't you just make a Pull Request?

**Comment by KingYes** [comment]
You can take my code from my Fork.

**Comment by stephenharris** [comment]
Sorry @KingYes, I never replied to this. Thanks for letting me know about your fork, but I think I shall leave this. I just feel it's slightly "off track" for the plug-in's original purpose, but undoubtedly your fork will be very useful to those who are using GitHub, and using Travis with their project and helps them add those icons while keeping their readme.txt clean.
