### ISSUE TITLE
Trailing spaces

### ISSUE THREAD

**Issue by rdoursenaud** [stephenharris/wp-readme-to-markdown#9]
Conversion generates some lines with trailing spaces.

See a sample result in this repo: https://github.com/GPCsolutions/doliwoo/commit/ab4b43319124ca67d31fbfefbeaba523e6d70c37

**Comment by stephenharris** [comment]
Hi @rdoursenaud, that's intentional. Two trailing spaces at the end of the line is equivalent (in HTML) to inserting a line break.

**Comment by rdoursenaud** [comment]
You mean in Markdown ;) I didn't knew that. Thanks!

**Comment by stephenharris** [comment]
Well I meant trailing spaces in Markdown renders as a line break when converted to HTML, but yeah :)
